//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEF.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerID { get; set; }
        public int PersonID { get; set; }
        public int StoreID { get; set; }
        public int TerritoryID { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int EmployeeBusinessEntityID { get; set; }
        public int StoreStoreID { get; set; }
    
        public virtual Persons_Employee Persons_Employee { get; set; }
        public virtual Store Store { get; set; }
    }
}
