//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEF.DatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BusinessDataBaseFirstEntities : DbContext
    {
        public BusinessDataBaseFirstEntities()
            : base("name=BusinessDataBaseFirstEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Departement> Departements { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Persons_Employee> Persons_Employee { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
    }
}
