//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEF.DatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int BusinessEntityID { get; set; }
        public string PersonType { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MidlleName { get; set; }
        public string LastName { get; set; }
        public int EmailPromotion { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Persons_Employee Persons_Employee { get; set; }
    }
}
